package migration

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"testing"

	"golang.org/x/mod/modfile"
)

const fixtureFerretVersion = "v2.0.0-alpha.44"

func TestMigratorRewritesEverySupportedCompatibilityImport(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret v1.0.0
`, map[string]string{
		"main.go": `// Package app keeps this comment.
package app

import (
	"fmt"

	"github.com/MontFerret/ferret"
	"github.com/MontFerret/ferret/pkg/compiler"
	_ "github.com/MontFerret/ferret/pkg/runtime"
	. "github.com/MontFerret/ferret/pkg/runtime/core"
	values "github.com/MontFerret/ferret/pkg/runtime/values"
	"github.com/MontFerret/ferret/pkg/runtime/values/types"
)

var _ = fmt.Sprintf
`,
	})

	migrator, runner := newFixtureMigrator()
	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if !result.Applied || result.UpdatedImports != 6 || result.FormattedFiles != 1 {
		t.Fatalf("unexpected result: %#v", result)
	}
	if runner.getCalls != 1 {
		t.Fatalf("expected one dependency resolution, got %d", runner.getCalls)
	}

	source := readMigrationFixture(t, filepath.Join(root, "main.go"))
	for _, expected := range []string{
		`ferret "github.com/MontFerret/ferret/v2/compat"`,
		`"github.com/MontFerret/ferret/v2/compat/compiler"`,
		`_ "github.com/MontFerret/ferret/v2/compat/runtime"`,
		`. "github.com/MontFerret/ferret/v2/compat/runtime/core"`,
		`values "github.com/MontFerret/ferret/v2/compat/runtime/values"`,
		`"github.com/MontFerret/ferret/v2/compat/runtime/values/types"`,
		`// Package app keeps this comment.`,
		`"fmt"`,
	} {
		if !strings.Contains(source, expected) {
			t.Fatalf("expected migrated source to contain %q:\n%s", expected, source)
		}
	}

	parsed := parseMigrationFixtureMod(t, root)
	if version, _ := migrationRequirement(parsed, v1ModulePath); version != "" {
		t.Fatalf("expected v1 requirement to be removed, got %s", version)
	}
	if version, indirect := migrationRequirement(parsed, v2ModulePath); version != fixtureFerretVersion || indirect {
		t.Fatalf("unexpected v2 requirement: version=%q indirect=%v", version, indirect)
	}
	if sum := readMigrationFixture(t, filepath.Join(root, "go.sum")); !strings.Contains(sum, v2ModulePath+" "+fixtureFerretVersion) {
		t.Fatalf("expected v2 checksums, got:\n%s", sum)
	}
}

func TestMigratorPreservesExplicitRootImportAliases(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go": `package app

import legacy "github.com/MontFerret/ferret"

var _ = legacy.New
`,
	})

	migrator, _ := newFixtureMigrator()
	if _, err := migrator.Migrate(context.Background(), Options{Directory: root}); err != nil {
		t.Fatal(err)
	}

	source := readMigrationFixture(t, filepath.Join(root, "main.go"))
	if !strings.Contains(source, `legacy "github.com/MontFerret/ferret/v2/compat"`) {
		t.Fatalf("expected explicit alias to be preserved:\n%s", source)
	}
}

func TestMigratorReportsGeneratedAndUnsupportedImportsAndRetainsV1(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret v1.0.0
`, map[string]string{
		"main.go": `package app

import (
	"github.com/MontFerret/ferret"
	"github.com/MontFerret/ferret/pkg/drivers/cdp"
)
`,
		"generated.go": `// Code generated by fixture. DO NOT EDIT.
package app

import "github.com/MontFerret/ferret/pkg/runtime"

func generatedButMalformed(
`,
	})

	generatedBefore := readMigrationFixture(t, filepath.Join(root, "generated.go"))
	migrator, _ := newFixtureMigrator()
	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if len(result.ManualActions) != 2 {
		t.Fatalf("expected two manual actions, got %#v", result.ManualActions)
	}
	if result.ManualActions[0].Detail != "github.com/MontFerret/ferret/pkg/runtime" ||
		result.ManualActions[0].Reason != "generated file was not modified" ||
		result.ManualActions[1].Detail != "github.com/MontFerret/ferret/pkg/drivers/cdp" {
		t.Fatalf("unexpected manual actions: %#v", result.ManualActions)
	}
	if after := readMigrationFixture(t, filepath.Join(root, "generated.go")); after != generatedBefore {
		t.Fatalf("generated source changed:\n%s", after)
	}

	parsed := parseMigrationFixtureMod(t, root)
	if version, _ := migrationRequirement(parsed, v1ModulePath); version != "v1.0.0" {
		t.Fatalf("expected v1 requirement to remain, got %q", version)
	}
	if version, _ := migrationRequirement(parsed, v2ModulePath); version != fixtureFerretVersion {
		t.Fatalf("expected v2 requirement, got %q", version)
	}
}

func TestMigratorLeavesUnsupportedOnlyProjectsUntouched(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret v1.0.0
`, map[string]string{
		"main.go": `package app
import "github.com/MontFerret/ferret/pkg/drivers/http"
`,
	})
	before := snapshotMigrationFixture(t, root)
	migrator, runner := newFixtureMigrator()

	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Changes) != 0 || len(result.ManualActions) != 1 || runner.getCalls != 0 {
		t.Fatalf("unexpected result: %#v, get calls=%d", result, runner.getCalls)
	}
	assertMigrationFixtureUnchanged(t, root, before)
}

func TestMigratorExcludesVendorAndNestedModules(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go": `package app
import "github.com/MontFerret/ferret"
`,
		"vendor/example.com/dependency/dependency.go": `package dependency
import "github.com/MontFerret/ferret"
`,
		"nested/go.mod": `module example.com/nested

go 1.25.0
`,
		"nested/nested.go": `package nested
import "github.com/MontFerret/ferret"
`,
	})

	vendorPath := filepath.Join(root, "vendor/example.com/dependency/dependency.go")
	nestedPath := filepath.Join(root, "nested/nested.go")
	vendorBefore := readMigrationFixture(t, vendorPath)
	nestedBefore := readMigrationFixture(t, nestedPath)

	migrator, _ := newFixtureMigrator()
	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if !result.VendorDetected || result.ScannedFiles != 1 {
		t.Fatalf("unexpected discovery result: %#v", result)
	}
	if readMigrationFixture(t, vendorPath) != vendorBefore {
		t.Fatal("vendor source was modified")
	}
	if readMigrationFixture(t, nestedPath) != nestedBefore {
		t.Fatal("nested module source was modified")
	}
}

func TestMigratorIncludesBuildConstrainedModuleFiles(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go": "package app\n",
		"platform_windows.go": `//go:build windows

package app

import "github.com/MontFerret/ferret/pkg/runtime"
`,
		"tools/tool_windows.go": `//go:build windows

package tools

import "github.com/MontFerret/ferret/pkg/compiler"
`,
	})

	migrator, _ := newFixtureMigrator()
	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if result.ScannedFiles != 3 || result.UpdatedImports != 2 {
		t.Fatalf("unexpected result: %#v", result)
	}
	source := readMigrationFixture(t, filepath.Join(root, "platform_windows.go"))
	if !strings.Contains(source, "github.com/MontFerret/ferret/v2/compat/runtime") {
		t.Fatalf("build-constrained file was not migrated:\n%s", source)
	}
	toolsSource := readMigrationFixture(t, filepath.Join(root, "tools/tool_windows.go"))
	if !strings.Contains(toolsSource, "github.com/MontFerret/ferret/v2/compat/compiler") {
		t.Fatalf("ignored-only package file was not migrated:\n%s", toolsSource)
	}
}

func TestMigratorHandlesNoopAndAlreadyMigratedProjects(t *testing.T) {
	tests := []struct {
		name   string
		goMod  string
		source string
	}{
		{
			name: "no Ferret imports",
			goMod: `module example.com/app

go 1.25.0
`,
			source: `package app
import "fmt"
var _ = fmt.Sprintf
`,
		},
		{
			name: "already migrated",
			goMod: `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret/v2 v2.0.0-alpha.44
`,
			source: `package app
import ferret "github.com/MontFerret/ferret/v2/compat"
var _ = ferret.New
`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := writeMigrationFixture(t, tt.goMod, map[string]string{"main.go": tt.source})
			before := snapshotMigrationFixture(t, root)
			migrator, runner := newFixtureMigrator()

			result, err := migrator.Migrate(context.Background(), Options{Directory: root})
			if err != nil {
				t.Fatal(err)
			}

			if len(result.Changes) != 0 || result.Applied || runner.getCalls != 0 {
				t.Fatalf("unexpected no-op result: %#v, get calls=%d", result, runner.getCalls)
			}
			assertMigrationFixtureUnchanged(t, root, before)
		})
	}
}

func TestMigratorDoesNotUpgradeAlreadyMigratedCompatDependency(t *testing.T) {
	const existingVersion = "v2.0.0-alpha.43"

	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret/v2 v2.0.0-alpha.43
`, map[string]string{
		"go.sum": `github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbKJ3jJ8ytPNgQxk1Sc1Z/TcxLB0wY=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZqGeKgJRHDYQ=
`,
		"main.go": `package app
import ferret "github.com/MontFerret/ferret/v2/compat"
var _ = ferret.New
`,
	})
	before := snapshotMigrationFixture(t, root)
	migrator, runner := newFixtureMigrator()

	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Changes) != 0 || result.Applied || result.DependenciesChanged {
		t.Fatalf("unexpected no-op result: %#v", result)
	}
	if runner.getCalls != 0 {
		t.Fatalf("expected no go get calls, got %d", runner.getCalls)
	}
	assertMigrationFixtureUnchanged(t, root, before)

	parsed := parseMigrationFixtureMod(t, root)
	if version, indirect := migrationRequirement(parsed, v2ModulePath); version != existingVersion || indirect {
		t.Fatalf("unexpected v2 requirement: version=%q indirect=%v", version, indirect)
	}
}

func TestMigratorUsesCLIEmbeddedVersionAsFloorDuringMigration(t *testing.T) {
	tests := []struct {
		name     string
		existing string
		indirect bool
		want     string
	}{
		{
			name:     "upgrade older",
			existing: "v2.0.0-alpha.43",
			want:     fixtureFerretVersion,
		},
		{
			name:     "preserve newer",
			existing: "v2.0.0-alpha.45",
			want:     "v2.0.0-alpha.45",
		},
		{
			name:     "promote indirect",
			existing: fixtureFerretVersion,
			indirect: true,
			want:     fixtureFerretVersion,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			indirect := ""
			if tt.indirect {
				indirect = " // indirect"
			}

			root := writeMigrationFixture(t, fmt.Sprintf(`module example.com/app

go 1.25.0

require (
	github.com/MontFerret/ferret v1.0.0
	github.com/MontFerret/ferret/v2 %s%s
)
`, tt.existing, indirect), map[string]string{
				"main.go": `package app
import "github.com/MontFerret/ferret"
var _ = ferret.New
`,
			})

			migrator, runner := newFixtureMigrator()
			result, err := migrator.Migrate(context.Background(), Options{Directory: root})
			if err != nil {
				t.Fatal(err)
			}

			if len(result.Changes) == 0 || !result.DependenciesChanged || result.UpdatedImports != 1 {
				t.Fatalf("unexpected result: %#v", result)
			}
			if runner.getCalls != 1 {
				t.Fatalf("expected one go get call, got %d", runner.getCalls)
			}

			parsed := parseMigrationFixtureMod(t, root)
			if version, indirect := migrationRequirement(parsed, v2ModulePath); version != tt.want || indirect {
				t.Fatalf("unexpected v2 requirement: version=%q indirect=%v", version, indirect)
			}
			if version, _ := migrationRequirement(parsed, v1ModulePath); version != "" {
				t.Fatalf("expected v1 requirement to be removed, got %s", version)
			}
		})
	}
}

func TestMigratorDryRunAndPrintDoNotWriteProjectFiles(t *testing.T) {
	for _, mode := range []Mode{ModeDryRun, ModePrint} {
		t.Run(fmt.Sprintf("mode %d", mode), func(t *testing.T) {
			root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret v1.0.0
`, map[string]string{
				"main.go": `package app
import "github.com/MontFerret/ferret"
`,
			})
			before := snapshotMigrationFixture(t, root)
			migrator, _ := newFixtureMigrator()

			result, err := migrator.Migrate(context.Background(), Options{Directory: root, Mode: mode})
			if err != nil {
				t.Fatal(err)
			}

			if len(result.Changes) == 0 || result.Applied {
				t.Fatalf("unexpected preview result: %#v", result)
			}
			assertMigrationFixtureUnchanged(t, root, before)
		})
	}
}

func TestMigratorIsIdempotent(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret v1.0.0
`, map[string]string{
		"main.go": `package app
import "github.com/MontFerret/ferret"
`,
	})

	migrator, runner := newFixtureMigrator()
	first, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}
	if !first.Applied {
		t.Fatal("expected first migration to apply changes")
	}

	afterFirst := snapshotMigrationFixture(t, root)
	second, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if len(second.Changes) != 0 || second.Applied || runner.getCalls != 1 {
		t.Fatalf("unexpected second result: %#v, get calls=%d", second, runner.getCalls)
	}
	assertMigrationFixtureUnchanged(t, root, afterFirst)
}

func TestMigratorPreservesModifiedFileModes(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go": `package app
import "github.com/MontFerret/ferret"
`,
	})
	goModPath := filepath.Join(root, "go.mod")
	sourcePath := filepath.Join(root, "main.go")
	if err := os.Chmod(goModPath, 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(sourcePath, 0o600); err != nil {
		t.Fatal(err)
	}

	migrator, _ := newFixtureMigrator()
	if _, err := migrator.Migrate(context.Background(), Options{Directory: root}); err != nil {
		t.Fatal(err)
	}

	for path, want := range map[string]os.FileMode{goModPath: 0o640, sourcePath: 0o600} {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		if got := info.Mode().Perm(); got != want {
			t.Fatalf("expected %s mode %o, got %o", path, want, got)
		}
	}
}

func TestMigratorWithGoToolchain(t *testing.T) {
	if os.Getenv("FERRET_MIGRATION_INTEGRATION") == "" {
		t.Skip("set FERRET_MIGRATION_INTEGRATION=1 to exercise staged dependency resolution")
	}

	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go": `package app
import "github.com/MontFerret/ferret"
`,
	})
	runner := execGoRunner{}
	migrator := &Migrator{planner: newV1ToV2Planner(runner, func() (string, error) {
		return fixtureFerretVersion, nil
	})}

	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Applied || !result.DependenciesChanged {
		t.Fatalf("unexpected result: %#v", result)
	}

	second, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}
	if len(second.Changes) != 0 {
		t.Fatalf("expected idempotent second run, got %#v", second.Changes)
	}
}

func TestMigratorAppliesPureFQLMigrationWithoutChangingDependencies(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go": "package app\n",
		"query.fql": `FOR x IN 1..3
    RETURN x`,
	})
	goModBefore := readMigrationFixture(t, filepath.Join(root, "go.mod"))
	migrator, runner := newFixtureMigrator()

	first, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if !first.Applied || first.ScannedFQLFiles != 1 || first.MigratedFQLFiles != 1 ||
		first.DependenciesChanged || runner.getCalls != 0 {
		t.Fatalf("unexpected FQL migration result: %#v, get calls=%d", first, runner.getCalls)
	}

	if got := readMigrationFixture(t, filepath.Join(root, "query.fql")); got != `return for x in 1..3 {
    return x
}` {
		t.Fatalf("unexpected migrated FQL:\n%s", got)
	}

	if got := readMigrationFixture(t, filepath.Join(root, "go.mod")); got != goModBefore {
		t.Fatalf("pure FQL migration changed go.mod:\n%s", got)
	}

	second, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if second.Applied || second.MigratedFQLFiles != 0 || len(second.Changes) != 0 || runner.getCalls != 0 {
		t.Fatalf("second migration was not a no-op: %#v, get calls=%d", second, runner.getCalls)
	}
}

func TestMigratorAppliesGoAndFQLChangesTogether(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0

require github.com/MontFerret/ferret v1.0.0
`, map[string]string{
		"main.go": `package app
import "github.com/MontFerret/ferret"
`,
		"query.fql": `LET values = 1..3
FOR value IN values
    RETURN value`,
	})
	migrator, runner := newFixtureMigrator()

	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if !result.Applied || result.UpdatedImports != 1 || result.MigratedFQLFiles != 1 ||
		!result.DependenciesChanged || runner.getCalls != 1 {
		t.Fatalf("unexpected mixed migration result: %#v, get calls=%d", result, runner.getCalls)
	}

	paths := make([]string, len(result.Changes))
	for index, change := range result.Changes {
		paths[index] = change.Path
	}

	wantPaths := []string{"go.mod", "go.sum", "main.go", "query.fql"}
	if !slices.Equal(paths, wantPaths) {
		t.Fatalf("mixed migration paths = %v, want %v", paths, wantPaths)
	}
}

func TestMigratorFQLDiscoveryPreservesExistingExclusions(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go":                       "package app\n",
		"query.fql":                     "FOR x IN 1..3 RETURN x",
		"vendor/dependency/vendor.fql":  "FOR x IN 1..3 RETURN x",
		"testdata/fixture.fql":          "FOR x IN 1..3 RETURN x",
		"node_modules/module/query.fql": "FOR x IN 1..3 RETURN x",
		".hidden/query.fql":             "FOR x IN 1..3 RETURN x",
		"_generated/query.fql":          "FOR x IN 1..3 RETURN x",
		"upper.FQL":                     "FOR x IN 1..3 RETURN x",
		"nested/go.mod":                 "module example.com/nested\n\ngo 1.25.0\n",
		"nested/query.fql":              "FOR x IN 1..3 RETURN x",
	})
	excluded := []string{
		"vendor/dependency/vendor.fql",
		"testdata/fixture.fql",
		"node_modules/module/query.fql",
		".hidden/query.fql",
		"_generated/query.fql",
		"upper.FQL",
		"nested/query.fql",
	}
	before := make(map[string]string, len(excluded))
	for _, path := range excluded {
		before[path] = readMigrationFixture(t, filepath.Join(root, path))
	}

	migrator, _ := newFixtureMigrator()
	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if result.ScannedFQLFiles != 1 || result.MigratedFQLFiles != 1 {
		t.Fatalf("unexpected FQL discovery result: %#v", result)
	}

	for _, path := range excluded {
		if got := readMigrationFixture(t, filepath.Join(root, path)); got != before[path] {
			t.Fatalf("excluded FQL file %s changed:\n%s", path, got)
		}
	}
}

func TestMigratorReportsMalformedFQLAndContinues(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go":   "package app\n",
		"valid.fql": "FOR x IN 1..3 RETURN x",
		"broken.fql": `LET ok = 1
FOR x IN
    RETURN x`,
	})
	brokenBefore := readMigrationFixture(t, filepath.Join(root, "broken.fql"))
	migrator, _ := newFixtureMigrator()

	result, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if !result.Applied || result.ScannedFQLFiles != 2 || result.MigratedFQLFiles != 1 ||
		len(result.ManualActions) != 1 {
		t.Fatalf("unexpected malformed FQL result: %#v", result)
	}

	action := result.ManualActions[0]
	if action.Path != "broken.fql" || action.Line < 2 || action.Detail == "" {
		t.Fatalf("unexpected manual action: %#v", action)
	}

	if got := readMigrationFixture(t, filepath.Join(root, "broken.fql")); got != brokenBefore {
		t.Fatalf("malformed FQL changed:\n%s", got)
	}

	if got := readMigrationFixture(t, filepath.Join(root, "valid.fql")); !strings.HasPrefix(got, "return for") {
		t.Fatalf("valid FQL was not migrated:\n%s", got)
	}
}

func TestMigratorFQLDryRunDoesNotWriteAndPreservesModeOnApply(t *testing.T) {
	root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
		"main.go":   "package app\n",
		"query.fql": "FOR x IN 1..3 RETURN x",
	})
	path := filepath.Join(root, "query.fql")
	if err := os.Chmod(path, 0o600); err != nil {
		t.Fatal(err)
	}
	before := readMigrationFixture(t, path)
	migrator, _ := newFixtureMigrator()

	preview, err := migrator.Migrate(context.Background(), Options{Directory: root, Mode: ModeDryRun})
	if err != nil {
		t.Fatal(err)
	}

	if preview.Applied || preview.MigratedFQLFiles != 1 || readMigrationFixture(t, path) != before {
		t.Fatalf("dry run mutated FQL: %#v", preview)
	}

	applied, err := migrator.Migrate(context.Background(), Options{Directory: root})
	if err != nil {
		t.Fatal(err)
	}

	if !applied.Applied || applied.MigratedFQLFiles != 1 {
		t.Fatalf("unexpected applied result: %#v", applied)
	}

	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}

	if got := info.Mode().Perm(); got != 0o600 {
		t.Fatalf("FQL mode = %o, want 600", got)
	}
}

func TestMigratorRejectsMissingOrMalformedProjects(t *testing.T) {
	t.Run("missing go.mod", func(t *testing.T) {
		migrator, _ := newFixtureMigrator()
		_, err := migrator.Migrate(context.Background(), Options{Directory: t.TempDir()})
		if err == nil || !strings.Contains(err.Error(), "not inside a Go module") {
			t.Fatalf("unexpected error: %v", err)
		}
	})

	t.Run("malformed go.mod", func(t *testing.T) {
		root := writeMigrationFixture(t, "module [\n", map[string]string{
			"main.go": "package app\n",
		})
		migrator, _ := newFixtureMigrator()
		if _, err := migrator.Migrate(context.Background(), Options{Directory: root}); err == nil {
			t.Fatal("expected malformed go.mod error")
		}
	})

	t.Run("malformed Go source", func(t *testing.T) {
		root := writeMigrationFixture(t, `module example.com/app

go 1.25.0
`, map[string]string{
			"main.go": "package app\nfunc broken(\n",
		})
		migrator, _ := newFixtureMigrator()
		_, err := migrator.Migrate(context.Background(), Options{Directory: root})
		if err == nil || !strings.Contains(err.Error(), "parse") || !strings.Contains(err.Error(), "main.go") {
			t.Fatalf("unexpected error: %v", err)
		}
	})
}

func TestListMigrationFilesDoesNotHideEnumerationFailures(t *testing.T) {
	runner := &fixtureGoRunner{packageError: "cache unavailable"}
	_, err := listMigrationFiles(context.Background(), runner, t.TempDir())
	if err == nil || !strings.Contains(err.Error(), "cache unavailable") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCommitMigrationChangesRollsBackEarlierFiles(t *testing.T) {
	root := t.TempDir()
	firstPath := filepath.Join(root, "first.go")
	secondPath := filepath.Join(root, "query.fql")
	if err := os.WriteFile(firstPath, []byte("first-before"), 0o640); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(secondPath, []byte("second-before"), 0o600); err != nil {
		t.Fatal(err)
	}

	first := mustMigrationSnapshot(t, firstPath)
	second := mustMigrationSnapshot(t, secondPath)
	changes := []plannedChange{
		{
			change: Change{Path: "first.go", Before: first.Data, After: []byte("first-after"), BeforeExists: true},
			before: first,
			mode:   first.Mode,
		},
		{
			change: Change{Path: "query.fql", Before: second.Data, After: []byte("second-after"), BeforeExists: true},
			before: second,
			mode:   second.Mode,
		},
	}

	originalRename := renameMigrationFile
	calls := 0
	renameMigrationFile = func(oldPath, newPath string) error {
		calls++
		if calls == 2 {
			return errors.New("replacement failed")
		}

		return os.Rename(oldPath, newPath)
	}
	t.Cleanup(func() { renameMigrationFile = originalRename })

	if err := commitMigrationChanges(changes); err == nil || !strings.Contains(err.Error(), "replacement failed") {
		t.Fatalf("unexpected error: %v", err)
	}
	if got := readMigrationFixture(t, firstPath); got != "first-before" {
		t.Fatalf("first file was not rolled back: %q", got)
	}
	if got := readMigrationFixture(t, secondPath); got != "second-before" {
		t.Fatalf("second file changed: %q", got)
	}
}

func BenchmarkPlanSourceChanges(b *testing.B) {
	root := b.TempDir()
	files := make([]string, 100)
	for index := range files {
		filename := filepath.Join(root, fmt.Sprintf("file_%03d.go", index))
		source := fmt.Sprintf(`package app

import "github.com/MontFerret/ferret/pkg/runtime/values"

// Value%d keeps representative source around the migrated import.
var Value%d = values.NewInt(%d)
`, index, index, index)
		if err := os.WriteFile(filename, []byte(source), 0o644); err != nil {
			b.Fatal(err)
		}
		files[index] = filename
	}

	project := &migrationProject{Root: root, GoFiles: files}
	b.ResetTimer()

	for range b.N {
		result, err := planGoSourceChanges(context.Background(), project)
		if err != nil {
			b.Fatal(err)
		}

		if result.UpdatedImports != len(files) {
			b.Fatalf("expected %d imports, got %d", len(files), result.UpdatedImports)
		}
	}
}

func BenchmarkPlanFQLSourceChanges(b *testing.B) {
	root := b.TempDir()
	files := make([]string, 100)
	for index := range files {
		filename := filepath.Join(root, fmt.Sprintf("query_%03d.fql", index))
		source := fmt.Sprintf(`LET seed = %d
FOR value IN 1..100 {
    FILTER value > seed
    RETURN value * 2
}`, index)
		if err := os.WriteFile(filename, []byte(source), 0o644); err != nil {
			b.Fatal(err)
		}
		files[index] = filename
	}

	project := &migrationProject{Root: root, FQLFiles: files}
	b.ResetTimer()

	for range b.N {
		result, err := planFQLSourceChanges(context.Background(), project)
		if err != nil {
			b.Fatal(err)
		}

		if result.MigratedFiles != len(files) {
			b.Fatalf("expected %d FQL migrations, got %d", len(files), result.MigratedFiles)
		}
	}
}

type fixtureGoRunner struct {
	packageError string
	getCalls     int
}

func (runner *fixtureGoRunner) Run(ctx context.Context, directory string, args ...string) ([]byte, error) {
	if runner.packageError != "" && len(args) > 0 && args[0] == "list" {
		return []byte(fmt.Sprintf(
			`{"ImportPath":"example.com/app","Incomplete":true,"Error":{"Err":%q}}`,
			runner.packageError,
		)), nil
	}

	if len(args) == 0 || args[0] != "get" {
		return (execGoRunner{}).Run(ctx, directory, args...)
	}

	runner.getCalls++
	if len(args) != 3 || !strings.HasPrefix(args[1], "-modfile=") {
		return nil, fmt.Errorf("unexpected go get arguments: %q", args)
	}

	modPath := strings.TrimPrefix(args[1], "-modfile=")
	queryAt := strings.LastIndex(args[2], "@")
	if queryAt < 0 {
		return nil, fmt.Errorf("dependency query does not include a version: %q", args[2])
	}
	version := args[2][queryAt+1:]

	data, err := os.ReadFile(modPath)
	if err != nil {
		return nil, err
	}
	file, err := modfile.Parse(modPath, data, nil)
	if err != nil {
		return nil, err
	}
	setMigrationRequirements(file, version, false)
	file.Cleanup()
	formatted, err := file.Format()
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(modPath, formatted, 0o644); err != nil {
		return nil, err
	}

	sumPath := strings.TrimSuffix(modPath, ".mod") + ".sum"
	sumLine := fmt.Sprintf(
		"%s %s h1:iuizFAAo2rQ26HWisB0qtsP5rxJ45bHH6qBr14TyUUU=\n"+
			"%s %s/go.mod h1:IjoBKZuRggOvP+beDB4FPosw2NAq/EYabdaHpUVtfmY=\n",
		v2ModulePath,
		version,
		v2ModulePath,
		version,
	)
	existing, err := os.ReadFile(sumPath)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	if !bytes.Contains(existing, []byte(sumLine)) {
		existing = append(existing, sumLine...)
	}
	if err := os.WriteFile(sumPath, existing, 0o644); err != nil {
		return nil, err
	}

	return nil, nil
}

func newFixtureMigrator() (*Migrator, *fixtureGoRunner) {
	runner := new(fixtureGoRunner)
	planner := newV1ToV2Planner(runner, func() (string, error) {
		return fixtureFerretVersion, nil
	})

	return &Migrator{planner: planner}, runner
}

func writeMigrationFixture(t *testing.T, goMod string, files map[string]string) string {
	t.Helper()

	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte(goMod), 0o644); err != nil {
		t.Fatal(err)
	}

	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	return root
}

func readMigrationFixture(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	return string(data)
}

func parseMigrationFixtureMod(t *testing.T, root string) *modfile.File {
	t.Helper()

	path := filepath.Join(root, "go.mod")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	file, err := modfile.Parse(path, data, nil)
	if err != nil {
		t.Fatal(err)
	}

	return file
}

func snapshotMigrationFixture(t *testing.T, root string) map[string][]byte {
	t.Helper()

	result := make(map[string][]byte)
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}

		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		result[filepath.ToSlash(relative)] = data

		return nil
	})
	if err != nil {
		t.Fatal(err)
	}

	return result
}

func assertMigrationFixtureUnchanged(t *testing.T, root string, before map[string][]byte) {
	t.Helper()

	after := snapshotMigrationFixture(t, root)
	if len(after) != len(before) {
		t.Fatalf("fixture file count changed: before=%d after=%d", len(before), len(after))
	}

	paths := make([]string, 0, len(before))
	for path := range before {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		if !bytes.Equal(before[path], after[path]) {
			t.Fatalf("%s changed:\nbefore:\n%s\nafter:\n%s", path, before[path], after[path])
		}
	}
}

func mustMigrationSnapshot(t *testing.T, path string) fileSnapshot {
	t.Helper()

	snapshot, err := snapshotMigrationFile(path)
	if err != nil {
		t.Fatal(err)
	}

	return snapshot
}
